# Generated by Django 3.2.7 on 2021-10-04 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='short_code',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
